sora32127/healthy-person-emulator-dotorg

- app/routes/_layout.archives.$postId.tsx
- prisma/schema.prisma
投稿通知Bot側で作成した画像をS3経由でOGP画像として利用できるように変更した #9
> Configure OGP URL Dynamically

- app/components/CommentCard.tsx
コメント欄において、改行文字が改行として反映されない事象が発生していた。
whitespace属性を設定して改行が反映されることを確認した。
#15
> Add whitespace property to CommentCard

- app/components/CommentCard.tsx
長めのコメントだと枠外にはみ出すので、wrapするようにした
> Change whitespace property from pre to pre-wrap in CommentCard

- public/ads.txt
- public/robots.txt
- public/sitemap.xml
以下のファイルを作成し、Botによるクローリングに対応する
- ads.txt
- robots.txt
- sitemap.xml
なお、sitemap.xmlの動的な作成はできなかったので、残りの課題とする。
#19
> Botエージェント用ファイルの作成

- .github/workflows/playwright-test.yml
- package-lock.json
- package.json
- playwright.config.ts
- tests/readOnlyTest.spec.ts
- tests/writeTest.spec.ts
- Playwrightのコードがよくわからないタイミングで落ちていたので、修正を行った
- リファクタリングも行った
- ローカル環境で正常に動くことは確認済み
> Playwrightのコードを変更した

- .github/workflows/playwright-test.yml
- app/components/CommentCard.tsx
- app/components/ThemeSwitcher.tsx
- app/routes/_layout.tsx
- package-lock.json
- package.json
- playwright.config.ts
- tests/axeTest.spec.ts
- tests/writeTest.spec.ts
- うまく動作していなかったテストコードを改善した
- 自動でアクセシビリティチェックを実行するようにした
- e2eテストの発動条件を自動から手動に変更した
> Playwrightのテストを改善

- app/routes/_layout.readme.tsx
- Bluesky、Twitterでの更新通知Botの存在を示す文章をガイドラインに追加した
> SNS連携についてガイドラインを追記

- .github/workflows/playwright-test.yml
- app/components/SubmitFormComponents/StaticTextInput.tsx
- app/components/SubmitFormComponents/TextInputBoxAI.tsx
- app/routes/_layout.post.tsx
- app/routes/api.ai.getCompletion.tsx
- package-lock.json
- package.json
- tests/writeTest.spec.ts
- OpenAI gpt3.5-turboを利用して入力補助機能を追加した
> AI入力補助機能を追加

- Dockerfile
- README.md
- docker-compose.yml
- localdev.sh
- package.json
I like this product but set up part seems a bit messy for me. So I wrapped up all of them with docker.
Now you can do `docker compose up` to make it work in virtual environment.
Note that you must run `docker compose down` after running it due to the docker-in-docker approach.
> Dockerize app for better developing experience

- app/modules/embedding.server.ts
Supabaseのクライアントを利用してembeddingを更新する際、たまに`permission denied for schema public`が出現する。 このエラーに対応するため、prismaのクライアントを利用する。
> Replace supabase client with prisma client

- app/components/SubmitFormComponents/TagSelectionBox.tsx
- app/routes/_layout.archives.edit.$postId.tsx
- app/routes/_layout.signup.tsx
- package-lock.json
- package.json
- 編集ページで発生していたeslintエラーを修正
- 編集ページのタグ選択方式を投稿ページのものと同じにした
- 編集できないエラーを修正した
> 編集ページに関するエラーを修正

- app/routes/_layout.signup.tsx
- app/routes/_layout.userVerified.tsx
ユーザー登録後の導線がわかりづらかったため、本登録が完了したことを明示するページを作成した。
> Add userverifyed page

- app/routes/_layout.search.tsx
> Change tag initial state

- README.md
> chore: update misskey follow button icon

- README.md
> docs(readme): update x follow button icon

- app/components/ShareButtons.tsx
Share APIの発動時にタイトルを引き渡すように修正した
> Update: Add title as a new argment for Share API

- app/components/SubmitFormComponents/TextInputBoxAI.tsx
- app/routes/api.ai.getCompletion.tsx
- AI補完機能のプロンプトを英語にして精度を上げる
- 二つの選択肢を提示し、選択できるようにした
＃補足
- llamba-8bを利用してみたものの、精度が微妙だった
> Update AI Completion

- app/components/TagCard.tsx
- app/routes/_layout.archives.$postId.tsx
- app/routes/api.ai.getCompletion.tsx
- prisma/schema.prisma
- 投稿フォームの使用モデルをgpt3.5 turboからgpt4oに変更した
- サジェスチョンの履歴を保持するためのテーブルを追加し、サジェスト時に履歴を作成するようにした
- 類似記事フェッチ時にエラーが発生した場合、明示的にエラーコードを返すように変更した
- タグをbadgeとして扱うようにCSSを変更した
> 【機能追加】AIモデルを変更+misc

- app/components/SubmitFormComponents/TextInputBoxAI.tsx
- app/routes/_layout.archives.$postId.tsx
- app/routes/api.ai.createSuggestionCommitHistory.tsx
- prisma/schema.prisma
- AIサジェスチョンをコミットした際の履歴を保存するテーブルを作成
- コンポーネント側で履歴の保存動作を作成
> 【機能追加】AIサジェスチョンを利用した際の履歴を保存するようにした

- app/modules/embedding.server.ts
- app/routes/_layout.archives.edit.$postId.tsx
- app/routes/_layout.post.tsx
類似度検索の精度を上げるため、投稿タイトルとタグ名を含めるようにembeddingのロジックを変更した
> Update: Change embedding logic to inclue postTitle and tags

- README.md
> docs(readme)!: add link to shield-icons

- app/routes/_layout.post.tsx
Reverts sora32127/healthy-person-emulator-dotorg#61
以下のようなエラーが出るようになったのでRevertする
```text
TypeError: Cannot destructure property 'isLoggedIn' of 'x(...)' as it is null.
at N (https://healthy-person-emulator.org/assets/_layout-DKa7eGFB.js:1:19668)
at nu (https://healthy-person-emulator.org/assets/components-CqODPVmN.js:28:19504)
at cd (https://healthy-person-emulator.org/assets/components-CqODPVmN.js:30:43905)
at ad (https://healthy-person-emulator.org/assets/components-CqODPVmN.js:30:39686)
at em (https://healthy-person-emulator.org/assets/components-CqODPVmN.js:30:39614)
at Ci (https://healthy-person-emulator.org/assets/components-CqODPVmN.js:30:39468)
at wa (https://healthy-person-emulator.org/assets/components-CqODPVmN.js:30:35850)
at ld …
```
> Revert "Bugfix: Prevent multiple form submissions and disable submit button w…"

- app/components/SubmitFormComponents/TextInputBoxAI.tsx
APIの利用料金を減らすため、Copilot機能が発動するインターバルを長くする
> Update: Increase interval for suggestion timeout

- app/components/ShareButtons.tsx
- app/components/TagCard.tsx
- app/routes/_layout.archives.$postId.tsx
- app/routes/_layout.search.tsx
- app/routes/_layout.tsx
- tailwind.config.ts
- tests/readOnlyTest.spec.ts
見た目の変更を行った
- PC表示のレイアウトを変更
- メニューボタンのレイアウトを変更
- メニューボタンを押したときにアコーディオンアニメーションが出るようにした
- タグの表示で余計な枠線がついていたのを削除した
- 記事に対するいいね・よくないねボタンを押した際にアニメーションが発生するようにした
- ツールチップを追加した
> Fix layout

- app/components/ShareButtons.tsx
- app/components/TagCard.tsx
- app/routes/_layout.archives.$postId.tsx
- app/routes/_layout.search.tsx
- app/routes/_layout.tsx
- tailwind.config.ts
- tests/readOnlyTest.spec.ts
Reverts sora32127/healthy-person-emulator-dotorg#65
記事詳細が表示できなくなったためRevertする
> Revert "Fix layout"

- README.md
- package-lock.json
- #65 の変更を #69 でRevertしたのを打ち消した
- （変更を取り消したのを取り消した、つまり変更の適用を行った）
- Vercel内部のエラーで、`/archives/$postId`にアクセスしようとすると `Task Timeout` が発生した
- コード自体をRevertしても治らず、VercelでInstant Rollbackを行って復旧した
- Remixのバージョンを2.8.2から2.9.2にアップデートしてエラーが解消した
> 【hotfix】デプロイ時に発生したエラーの解消

- app/components/CommentCard.tsx
- app/components/CommentShowCard.tsx
- app/components/PostCard.tsx
- app/components/RelativeDate.tsx
- app/components/SubmitFormComponents/TagSelectionBox.tsx
- app/routes/_layout.archives.$postId.tsx
- app/routes/_layout.search.tsx
- app/routes/_layout.tsx
- 検索ボックスをヘッダーに表示するようにした
- 日付表示を絶対表示から相対表示に変更した
- コメント表示・投稿表示に時計アイコンを追加した
> 【UI変更】検索UI・日付表示の改善

- app/components/CommentShowCard.tsx
- app/components/Headings.tsx
- app/components/PostCard.tsx
- app/routes/_layout._index.tsx
- tailwind.config.ts
- ダークモードの背景色を#0F0F0Fに変更した
- トップページの見た目を変更した
> 【見た目変更】トップページ・背景色を変更

- app/root.tsx
- app/routes/_layout.archives.$postId.tsx
- app/routes/_layout.forgotPassword.tsx
- app/routes/_layout.login.tsx
- app/routes/_layout.resetPassword.tsx
- app/routes/_layout.signup.tsx
- app/routes/_layout.tsx
- app/tailwind.css
- tailwind.config.ts
- いいね・よくないねボタンのスタイルを変更した
- ボーダーを削除した
- 背景色を `bg-base-300` にした
- ホバー時の背景色を `bg-base-200` にした
- PC表示のサイドバーのスタイルを変更した
- ホバー時に背景色が明るくなるようにした
- ホバー時にテキストの色が変わる仕様を削除した
-  フォントを変更した
- Yu GothicからNoto Sansに変更した
- ログイン処理を行う際のフォームにautocomplete属性を付与した
- スマートフォン表示時のメニューをdaisyUI.drawerを利用するように変更した
- 「投稿する」ボタンをわかりやすくした
> 【Style】UIの改善

- app/routes/_layout.tsx
- 投稿するボタンを下にした
- メニューとコンテンツの間にborderを追加した
> 【Style】PC表示のレイアウトを調整

- app/routes/_layout.signup.verify-email-address.tsx
- app/routes/_layout.signupVerified.tsx
サインアップした後404に飛んでしまうため、サインアップ後のフローを追加した
> Fix: Add signup verify page

- app/routes/_layout.signupVerified.tsx
ユーザー登録を完了した段階ではログインは完了しない仕様に合わせ、文言を変更した
> Fix: Change text in signupVerify page

- app/components/CommentCard.tsx
- app/components/CommentInputBox.tsx
- app/routes/_layout.archives.$postId.tsx
コメント入力時、もしくはコメントに対するいいね・よくないねボタンを押した際に、CF Turnstileによるバリデーションが行われるようにした
> コメント入力時・コメント評価時にCloudflare TurnstileによるValidationを追加

- app/routes/_layout.freeStylePost.tsx
- 自由記述投稿ページにMetafunctionを追加
- 設定漏れによるもの
> Update: Add metafunction to Freestyle post page

- app/routes/_layout.archives.$postId.tsx
- app/routes/api.verify.tsx
Response.json()する際のエラーハンドリングができていなかったため、異常なレスポンスが返ってきたときにユーザーに対して「不明なエラーが発生しました」と出てしまっていたのを修正
> Bugfix: Fix parse error while verifying request

- app/components/PostCard.tsx
- app/routes/_layout.tsx
> Apply grid layout for PostCard

- app/components/CommentCard.tsx
- app/root.tsx
- app/routes/_layout.tsx
> 【レイアウト変更】横幅が崩れる問題に対応した

- app/routes/_layout.archives.edit.$postId.tsx
Markedのアップデートにより、カスタムレンダラー用のインターフェースが変更され、`header` `body` の二つの引数を取るのではなく`token`の一つの引数だけを取る形式になった。
そのため、投稿を編集しようとした際に`TypeError: header.replace is not a function`が発生し、編集できない状態となっていた。
> Bugfix: Fix Editor markdown renderer

- app/modules/db.server.ts
- app/root.tsx
> Feature: Add 404 Error Handling

- app/routes/_layout.tsx
- サイト内検索と被るため、検索モーダルのバインドを変更した
- PC用レイアウトに検索の案内を追加した
> 検索のキーバインドを変更した

- app/routes/_layout.search.tsx
> Delete: Remove unused console.log

- app/components/CommentSection.tsx
- app/components/CommentShowCard.tsx
- app/components/PostSection.tsx
- app/modules/db.server.ts
- app/modules/db.test.ts
- app/routes/_layout._index.tsx
- app/routes/_layout.comment.tsx
- app/routes/_layout.feed.tsx
> コメントフィードページの追加

- app/routes/_layout._index.tsx
- app/routes/_layout.archives.$postId.tsx
- app/routes/_layout.comment.tsx
- app/routes/_layout.feed.tsx
- app/routes/_layout.freeStylePost.tsx
- app/routes/_layout.login.tsx
- app/routes/_layout.post.tsx
- app/routes/_layout.privacyPolicy.tsx
- app/routes/_layout.readme.tsx
- app/routes/_layout.search.tsx
- app/routes/_layout.support.tsx
- app/utils/commonMetafunction.ts
> Metafunctionを共通化し、titleのsuffixに「 - 健常者エミュレータ事例集」を追加した

- app/routes/_layout.post.tsx
> ストップワードを追加した

- app/modules/db.server.ts
- app/routes/_layout.post.tsx
- app/schemas/post.schema.ts
- prisma/schema.prisma
変更の概要
- ストップワードを管理画面から追加できるようにした
- DBから取得したストップワードを利用してスキーマバリデーションを実施するようにした
> ストップワード統合の実施

- app/routes/_layout.archives.$postId.tsx
> FIX：コメント時のIPアドレス取得処理を修正

- app/routes/_layout.post.tsx
- 以下のような状態が起きないようにする
[![Image from Gyazo](https://i.gyazo.com/57d6f409fe5c2cc7773a163142f38c9b.png)](https://gyazo.com/57d6f409fe5c2cc7773a163142f38c9b)
> 【Fix】任意項目のWikify時に空白文字列が入ってしまうのを修正する

- app/components/CommentCard.tsx
- app/components/CommentInputBox.tsx
- app/components/TurnstileModal.tsx
- app/modules/db.server.ts
- app/modules/security.server.ts
- app/modules/session.server.ts
- app/routes/_layout.archives.$postId.tsx
- 記事に対するいいね・よくないねボタンの位置を記事の下に変更した
- リファクタリングの実施
- Turnstileの検証をセッション単位で共通化した
> 【セキュリティパッチ】投稿ページのセキュリティ関連バグを治す&リファクタリング

- app/components/Footer.tsx
- app/routes/_layout.tsx
- Footerを切り分けてSocial情報を追加した
- 投稿ボタンが投稿ページで表示されないようにした
> Style: レイアウトのアップデート

- app/routes/_layout.tsx
- app/stores/auth.ts
- package.json
- pnpm-lock.yaml
> ユーザーの認証状態管理にjotaiを導入する

- app/components/ThemeSwitcher.tsx
- app/routes/_layout._index.tsx
- app/routes/_layout.tsx
- app/utils/itemMenu.ts
- package.json
- pnpm-lock.yaml
> Redesign：Layout

- app/routes/_layout.archives.$postId.tsx
- app/routes/_layout.tsx
> スマートフォンで記事ページを表示した際に横幅が出るのを防ぐ

- app/components/CommentCard.tsx
- app/routes/_layout.archives.$postId.tsx
> Style: 記事ページ内部のツールチップを削除する

- app/components/CommentCard.tsx
- app/components/RelativeDate.tsx
- app/components/VoteButton.tsx
- app/routes/_layout.archives.$postId.tsx
- app/routes/_layout.tsx
- 相対日付表示コンポーネントにおいて、ツールチップの位置を右にした
- VoteButtonコンポーネントを切りだした
- PC版メニューバーの背景色をbg-base-100にして、アイテムのy位置を調整した
> スタイルを微調整した

- app/components/SNSLinks.tsx
- app/modules/db.server.ts
- app/routes/_layout.archives.$postId.tsx
- 「投稿時の反応を見る」コンポーネントを追加した
- 初回連携時のSNS投稿を閲覧できるようになった
> 投稿時のSNSリンクを見る機能を追加した

- app/components/CommentCard.tsx
- app/components/CommentInputBox.tsx
- app/components/RelativeDate.tsx
- app/routes/_layout.archives.$postId.tsx
- app/tailwind.css
- package.json
- pnpm-lock.yaml
- 以下のケースにおいてtoastが表示されるようにした
- コメント投稿
- コメントに対する評価の投稿
- 記事に対する評価の投稿
- コメントのリプライ表示ボックスの動作をスムーズにした
> 投稿ページの各種アクションにtoastを追加した & コメントのリプライ表示をスムーズにした

- app/routes/_layout.post.tsx
> 投稿ページのtoastをわかりやすくする

- app/routes/_layout.post.tsx
> 投稿フォームのtoastの挙動を微修正 & フォームクリアが作動していなかったのを修正

- app/routes/_layout.post.tsx
> 投稿完了時のtoastが2重になっていたのを治す

- app/routes/_layout.post.tsx
- 投稿完了時にプレビュー表示のタイトルが消えてしまうのを治した
- 投稿完了時にフォームがクリアされないのを治した
> 投稿フォームに関する意図していない挙動を修正する

- app/components/SNSLinks.tsx
- app/routes/_layout.post.tsx
> 「SNSの反応」リンクの色を変える & 投稿ページの型エラーを治す

- app/modules/auth.google.server.ts
- app/modules/session.server.ts
- app/modules/visitor.server.ts
- app/routes/_layout._index.tsx
- app/routes/_layout.archives.$postId.tsx
- app/routes/_layout.archives.edit.$postId.tsx
- app/routes/api.googleLogin.tsx
- app/routes/auth.google.callback.tsx
- ページ閲覧画面からログインした際、編集画面にリダイレクトするようにした
> ログインロジックの変更

- app/routes/_layout.archives.$postId.tsx
- package.json
- pnpm-lock.yaml
- 未認証状態でBookmarkボタンを押した後、ログイン後に編集画面にリダイレクトされるのを治した
- 未検証状態でアクションボタンを押した際に、Turnstileモーダルが開かないのを治した
> Bookmarkボタンを押した際のリダイレクトの動作を治す & Turnstileモーダルの発動条件を見直す

- app/components/CommentSection.tsx
- app/components/PostCard.tsx
- app/components/PostSection.tsx
- app/routes/_layout._index.tsx
- app/routes/_layout.tsx
- 投稿カードのスタイルを調整した
- レスポンシブデザインのレイアウトを調整した
> 投稿カードのスタイルを調整した

- app/components/Footer.tsx
- app/modules/db.server.ts
- app/routes/_layout.commerceDisclosure.tsx
- app/routes/_layout.editHistory.tsx
- app/routes/_layout.mypage.tsx
- app/utils/itemMenu.ts
- package.json
- pnpm-lock.yaml
> 編集履歴ページを追加した
