sora32127/healthy-person-emulator-dotorg

app/routes/_layout.support.tsx, app/routes/_layout.tsx
Fix: #5 
ついでに `ogUrl` も `/beSponsor` のままだったので修正しました。
=> 「寄付する」リンク先の修正

app/routes/_layout.archives.$postId.tsx
TwiiterのみOGP画像に対応していたが、ほかの媒体でもOGPに対応できるよう修正した
=> og:image propertyを追加

app/components/CommentShowCard.tsx, app/components/PostCard.tsx, app/components/TagCard.tsx, app/routes/_layout.archives.$postId.tsx
- 記事ページ内部で表示する関連記事の数を9個から15個に変更した
- 関連記事から遷移するユーザーが多かったため
- PostCardの見た目を調整した
- フォントサイズを変更した
- 表示されるタグ数を最大5個までにして、ほかは省略されるようにした
=> 見た目の改修を行った

public/robots.txt
wordpress時代のクローリングが残ってnew relicのログのノイズになるため、robots.txtで明示的にクローリングを禁止した
=> Configure robots.txt

app/routes/_layout.archives.edit.$postId.tsx
=> [hotfix] 編集ページのエラーを修正

app/components/CommentInputBox.tsx
コメントの内容が空の状態でも投稿できてしまう状態となっていたため、コメントが空の時には入力を促すよう変更した。
=> Prevent comment content being null

app/routes/_layout._index.tsx, app/routes/_layout.feed.tsx, app/routes/_layout.tsx, tests/readOnlyTest.spec.ts
- 「無期限いいね順」を追加
- 過去に投稿された記事をいいね数順に閲覧できる機能
- フィードページをリファクタリング
- トップレイアウトに無期限いいね順へのリンクを追加
=> 【機能追加】無期限いいね順を追加

app/components/SubmitFormComponents/TagSelectionBox.tsx, app/routes/_layout.search.tsx
- 検索画面で、いいね数順/新着順に記事を並び替えられるようにした
- 検索画面のUIをdaisy UIで統一した
=> 【機能追加】検索画面でいいね数・新着順の並び替え機能を追加

app/routes/_layout.archives.$postId.tsx
`throw new Error`だとページの読み込みがとまるため、console.errorに変更した
=> 【hotfix】エラーの吐き出しのスタイルを変更

app/routes/_layout._index.tsx
- コミュニティ選の最新の投稿が表示されないのを治した
- findManyにおいて、何も指定していない場合は上限取得数が24となる（らしい）
- コミュニティ選の投稿数が25以上になり、最新の投稿が反映されない状態になっていたため、上限を引き上げた。
- コミュニティ選の並び順を変更した
- 変更前：投稿日の昇順
- 変更後：投稿日の降順
=> 【Update】コミュニティ選の表示を変更した

app/modules/db.server.ts
- prisma用のクライアントが常にグローバルに生成されると、ホットリロードのたびにコネクションプールが使われてしまい、結果としてコネクションプールがすぐ切れてしまう
- この問題を解消するため、prismaインスタンスがグローバルに生成されている場合は再度生成しないようにした
=> Fix: Enfore prisma client is single instanse

app/components/Modal.tsx, app/modules/db.server.ts, app/routes/_layout.post.tsx
- 投稿成功時にlocalstorageの中身をクリアするように変更した
- 投稿タイトルに「# (ハッシュタグ)」が含まれている場合、モーダルを表示して投稿をはじくようにした
- 投稿成功時にモーダルを表示してからリダイレクトするようにした
- prismaクライアントの型定義を追加
=> 投稿タイトルのバリデーションを追加 & 投稿時に内容をクリアするように変更

app/components/SubmitFormComponents/TagSelectionBox.tsx
- アクセシビリティの観点から、SVGにtitle要素を追加した
- タグ選択ボックス内部のアニメーション描画に時間がかかるため、delayの処理を入れた
=> Style: Add delay for layout transition

app/modules/db.server.ts
コメントに対する「よくないね」の動作は`voteType == -1`の場合に判定されるが、ロジックを凝集させたときに謝って`voteType==0`の場合で判定していた。
そのため、正確にコメントに対するよくないねの数が集計できていなかった。
=> Fix: Update comment vote calculation program

app/modules/db.server.ts, app/modules/db.test.ts, app/routes/_layout._index.tsx, app/routes/_layout.feed.tsx
- フィードページを改修した
- サーバーサイド
- 処理を `db.server.ts`に集めた
- テストを追加した
- フロントエンド
- コメント数を表示するようにした
- フィードタイプの選択は `select` 要素でやるようにした
- ページネーションの見た目を変更した
=> フィードページの改修

app/routes/_layout.post.tsx
- IPアドレスの暗号化をやめ、直に保存するようにした
- この変更により、CloudflareでIPアドレス制限を実施することが可能になる
=> 【セキュリティパッチ】IPアドレス保存処理を追加した

app/modules/security.server.ts, app/routes/_layout.archives.$postId.tsx, app/routes/_layout.post.tsx
- いままでの取得方式だと、CloudflareのIPアドレスを取得してしまい、IPバンの用途を満たさなかった
- headerのCF-Connecting-IPを利用してIPアドレスを取得するように変更する
=> IPアドレス取得処理をCF-Connecting-IPに対応する

app/components/CommentCard.tsx, app/routes/_layout.archives.$postId.tsx
- コメントに対して共有ボタンを追加し、Share API経由でシェアできるようにした
- 記事表示ページを改修し、location.hashにコメントIDが含まれている場合は当該コメントまで自動スクロールするようにした
=> コメント自体をシェアできるようにする

app/components/PostCard.tsx, app/modules/db.server.ts
- OG画像作成プログラムを改修し、縦横のピクセル幅を固定する仕様にした
- CLS対策のため、imgのwidthとheight属性を固定する。
=> 【CLS対策】投稿表示カードのimgタグの`width`と`height`属性の値を固定する

app/root.tsx, app/tailwind.css
- フォントファイルをGoogle Fontsからローカルに移行した
- フォントファイルの読み込みをpreloadにして、フォールバックによるレイアウトシフトを防いだ
- font-dispaly: optionalを設定し、100ミリ秒以内にフォントが読みこまれない場合は自動的にデフォルトフォントを利用するようにした
=> 【CLS対策】フォントファイルをPreloadしてフォールバックによるレイアウトシフトを防ぐ

app/components/ThemeSwitcher.tsx, app/root.tsx, app/stores/theme.ts, app/tailwind.css, public/nofrash.js
- ThemeSwicherをjotaiを利用して書き換えた
- localStorage内部のThemeの値とテーマの整合性を取るために発生していたちらつきを抑制する
=> ダークモード・ライトモード間の切り替えによるちらつきを抑制する

app/root.tsx
- 本番環境でnofrash.jsの読み込み順を見てみたところ、HTMLパースの完了後に読みこまれていた
- それでは意味がないので直す
=> Fix: Remove `async` and `defer` attribute to nofrash.js

app/root.tsx, app/stores/theme.ts
- SSRでダークモードに真面目に対応させるのは難易度が高い
- localStorageとの同期機能を削除し、状態として保持しないようにした
- ちらつきは抑えられる
=> 【ちらつき対策】Themeのlocalstorageとの同期を削除

app/components/CommonNavLink.tsx, app/components/PostCard.tsx, app/components/TagCard.tsx, app/routes/_layout.archives.$postId.tsx, app/routes/_layout.archives.edit.$postId.tsx, app/routes/_layout.tsx
- 編集導線をtoastでわかりやすくした
- モバイル版のヘッダーが改行されていたのでclampで直した
- viewTransitionAPIを使った
=> 編集導線をtoastでわかりやすくする & モバイル版のヘッダーが改行されていたのを修正 & viewTransitionAPIを使いまくる

app/routes/_layout.post.tsx
=> 投稿ページにおいて、「クリップボードにコピー」した結果がundefinedになるのを治す

app/components/CommentCard.tsx
コンセプトに感銘を受けました。微力ながらサイトの体験向上に貢献したいと思い #87 の修正を行いました。
- **コメントに対するいいねボタン・よくないねボタン** を押した際の振る舞いを **記事に対するいいねボタン・よくないねボタン** と同じものにしました。
- [記事に対するいいねボタン・よくないねボタンと同様の実装](https://github.com/sora32127/healthy-person-emulator-dotorg/blob/9fd097d6e01593ce71cb3a4b8fddabfb5aa2d98d/app/routes/_layout.archives.%24postId.tsx#L77-L106) を施しています。
- [`VoteButton`](https://github.com/D-ske104/healthy-person-emulator-dotorg/blob/main/app/components/VoteButton.tsx) コンポーネントを利用するように変更
- クリックイベントのハンドラ内でアニメーション、非活性の状態管理を「記事いいね」と同様の処理に変更
closed #87
- **コメントに対するいいねボタン・よくないねボタン** を押したときにアニメーションする（スクリーンショット の GIFアニメを参照）
- **コメントに対するいいねボタン・よくないねボタン** を押した後、ローカル supabase `fct_comment_vote_history` テーブルにレコードが作成される
- [fct_comment_vote_history_rows.csv](https://github.com/user-attachments/files/18814180/fct_comment_vote_hi …
=> ユーザーがコメントに対するいいねボタン・よくないねボタンを押したときのフィードバックをすぐに受けられるように変更

app/routes/_layout.post.tsx
スマートフォンでの横幅が足りないため、Input要素をtextareaに変更した
=> fix: :bug: dynamicTextInputのInput要素をTextareaに変更する
